### ISSUE TITLE
External Service Task handling with Camel

### ISSUE THREAD

**Issue by falko** [camunda/camunda-bpm-camel#28]
My current customer, could have used a way to let Camel behave as an [external task](https://docs.camunda.org/manual/latest/user-guide/process-engine/external-tasks/) worker, i.e. fetch tasks from Camunda and report back on them once they are completed or when errors occurred.

**Comment by RasPelikan** [comment]
Hi Falko,

I not sure what your issue is about. Maybe this could help you: https://github.com/RasPelikan/camunda-bpm-camel/tree/ExternalTasksConsumer?files=1

I extended the Camel extension right in that way. It is already reviewed by Bernd Rücker. At the moment I'm doing the last refactoring based on this review. Afterwards it can be merged and released. I can do that within the next week.

Stephan

**Comment by falko** [comment]
Hi Stephan,

that's exactly what I have been looking for. I would be happy to see 
that merged.

Cheers,
Falko

**Comment by berndruecker** [comment]
I have it on my radar - I hope to get to it soon after the roadshow!

**Comment by RasPelikan** [comment]
The feature is part of release 0.5.0, in the meantime available since end of february. There is also a [blog post](https://blog.camunda.org/post/2017/03/camunda-bpm-camel-0.5.0/) about it and detailed documentation in the current [README.MD](https://github.com/camunda/camunda-bpm-camel#camunda-bpmpoll-externaltasks-consuming-external-tasks).
